# Generated by Django 3.1.4 on 2021-01-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0002_sample_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplecategory',
            old_name='category',
            new_name='name',
        ),
    ]
