# Generated by Django 3.1.7 on 2022-01-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0003_auto_20210103_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplecategory',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='samplephoto',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='samplephoto',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
