# Generated by Django 3.1.7 on 2021-11-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=140)),
                ('news_information', models.TextField()),
                ('news_data', models.DateTimeField()),
            ],
        ),
    ]
