# Generated by Django 3.1.7 on 2021-12-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_page', '0002_auto_20211126_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
